##	Revenues and traffic

```{=latex}
\begin{table}[H]
\centering
\begingroup

\newcommand{\NumW}{1.25cm}
\newcommand{\LabelW}{5.2cm}
\newcommand{\HdrPad}{\fontsize{2pt}{2pt}\selectfont\textcolor{HeaderBlue}{(something)}}
\newcommand{\GrpHdr}[1]{%
  \color{white}\bfseries
  \shortstack{%
    \HdrPad\\
    #1\\
    \textcolor{HeaderBlue}{(something)}%
  }%
}

\setlength{\tabcolsep}{4pt}

\begin{tabularx}{\textwidth}{
  >{\raggedright\arraybackslash}p{\LabelW}
  >{\raggedleft\arraybackslash}p{\NumW}
  >{\raggedleft\arraybackslash}p{\NumW}
  >{\raggedleft\arraybackslash}p{\NumW}
  >{\raggedleft\arraybackslash}p{\NumW}
  >{\raggedleft\arraybackslash}p{\NumW}
  >{\raggedleft\arraybackslash}p{\NumW}
}

% Header row 1
\multicolumn{1}{>{\columncolor{HeaderBlue}}l}{\color{white}\bfseries} &
\multicolumn{2}{>{\columncolor{HeaderBlue}}c}{\GrpHdr{En-route}} &
\multicolumn{2}{>{\columncolor{HeaderBlue}}c}{\GrpHdr{Terminal}} &
\multicolumn{2}{>{\columncolor{HeaderBlue}}c}{\GrpHdr{Gate-to-gate}} \\
\noalign{\vskip -3.65ex}

% Underlines row (no shading)
\multicolumn{1}{l}{} &
\multicolumn{1}{c}{\smash{\color{white}\rule{1.4cm}{0.35pt}}} &
\multicolumn{1}{c}{\smash{\color{white}\rule{1.4cm}{0.35pt}}} &
\multicolumn{1}{c}{\smash{\color{white}\rule{1.4cm}{0.35pt}}} &
\multicolumn{1}{c}{\smash{\color{white}\rule{1.4cm}{0.35pt}}} &
\multicolumn{1}{c}{\smash{\color{white}\rule{1.4cm}{0.35pt}}} &
\multicolumn{1}{c}{\smash{\color{white}\rule{1.4cm}{0.35pt}}} \\
\noalign{\vskip -0.5ex}

% Header row 2
\multicolumn{1}{>{\columncolor{HeaderBlue}}l}{} &
\multicolumn{1}{>{\columncolor{HeaderBlue}}r}{\color{white}\bfseries € M} &
\multicolumn{1}{>{\columncolor{HeaderBlue}}r}{\color{white}\bfseries \%} &
\multicolumn{1}{>{\columncolor{HeaderBlue}}r}{\color{white}\bfseries € M} &
\multicolumn{1}{>{\columncolor{HeaderBlue}}r}{\color{white}\bfseries \%} &
\multicolumn{1}{>{\columncolor{HeaderBlue}}r}{\color{white}\bfseries € M} &
\multicolumn{1}{>{\columncolor{HeaderBlue}}r}{\color{white}\bfseries \%} \\

% Body
\multicolumn{1}{>{\columncolor{Stripe}}l}{Staff costs} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{5 427} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{66.8\%} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{1 529} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{65.1\%} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{6 956} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{66.5\%} \\

\multicolumn{1}{>{\columncolor{white}}l}{\hspace{1.5em}\textit{ATCOs in OPS employment costs}} &
\multicolumn{1}{>{\columncolor{white}}r}{2 653} &
\multicolumn{1}{>{\columncolor{white}}r}{n.a.} &
\multicolumn{1}{>{\columncolor{white}}r}{807} &
\multicolumn{1}{>{\columncolor{white}}r}{n.a.} &
\multicolumn{1}{>{\columncolor{white}}r}{3 460} &
\multicolumn{1}{>{\columncolor{white}}r}{n.a.} \\

\multicolumn{1}{>{\columncolor{Stripe}}l}{\hspace{1.5em}\textit{Other staff employment costs}} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{2 774} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{n.a.} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{722} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{n.a.} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{3 496} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{n.a.} \\

\multicolumn{1}{>{\columncolor{white}}l}{Non-staff operating costs} &
\multicolumn{1}{>{\columncolor{white}}r}{1 447} &
\multicolumn{1}{>{\columncolor{white}}r}{17.8\%} &
\multicolumn{1}{>{\columncolor{white}}r}{387} &
\multicolumn{1}{>{\columncolor{white}}r}{16.5\%} &
\multicolumn{1}{>{\columncolor{white}}r}{1 835} &
\multicolumn{1}{>{\columncolor{white}}r}{17.5\%} \\

\multicolumn{1}{>{\columncolor{Stripe}}l}{Depreciation costs} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{811} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{10.0\%} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{227} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{9.7\%} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{1 037} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{9.9\%} \\

\multicolumn{1}{>{\columncolor{white}}l}{Cost of capital} &
\multicolumn{1}{>{\columncolor{white}}r}{409} &
\multicolumn{1}{>{\columncolor{white}}r}{5.0\%} &
\multicolumn{1}{>{\columncolor{white}}r}{179} &
\multicolumn{1}{>{\columncolor{white}}r}{7.6\%} &
\multicolumn{1}{>{\columncolor{white}}r}{588} &
\multicolumn{1}{>{\columncolor{white}}r}{5.6\%} \\

\multicolumn{1}{>{\columncolor{Stripe}}l}{Exceptional items} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{25} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{0.3\%} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{27} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{1.2\%} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{52} &
\multicolumn{1}{>{\columncolor{Stripe}}r}{0.5\%} \\

% Total
\multicolumn{1}{>{\columncolor{Total}}l}{Total ATM/CNS provision costs} &
\multicolumn{1}{>{\columncolor{Total}}r}{8 119} &
\multicolumn{1}{>{\columncolor{Total}}r}{100.0\%} &
\multicolumn{1}{>{\columncolor{Total}}r}{2 349} &
\multicolumn{1}{>{\columncolor{Total}}r}{100.0\%} &
\multicolumn{1}{>{\columncolor{Total}}r}{10 468} &
\multicolumn{1}{>{\columncolor{Total}}r}{100.0\%} \\

\end{tabularx}
\endgroup
\end{table}

```

::: {.content-visible when-format="pdf"}
```{r c_bdown_gtable}
#| file: R/hlsr_c_bdown_gtable.R
#| echo: false
#| include: false
```


```{r c_bdown_gtable_latex}
#| echo: false
#| results: asis

cat(latex_table_costs(df = data_table_pdf))
```
:::
