---
title: "hlsr_rev_table"
output: html_document
---

```{css, echo=FALSE}

.reactable {
    margin-left: 15px;
    margin-right: 15px;
}

```


```{r, echo=FALSE, include=FALSE}
## libraries
library(tidyverse)
library("data.table")
library(dplyr)
library(readxl)
library(reactable)
library(htmltools)
library(janitor)
```

```{r, echo=FALSE, warning=FALSE}

## import data
data_raw  <-  read_xlsx("//sky.corp.eurocontrol.int/DFSRoot/Groups/HQ/dgof-pru/Project/ACE/Data for ACE landing page and digital reports/hlsr2021_data.xlsx",
                       sheet = "F_Revenue",
                       range = cell_limits(c(9, 1), c(NA, 4))) %>%
  as_tibble() %>% 
  rename(TYPE = 'Data', TOTAL = 'Grand Total') %>% 
  mutate(across(TYPE, str_replace, 'Sum of ', '')) %>% 
  filter( TYPE != "REVE_DELEGATION")

#sum rows
data_temp <- data_raw %>% filter(TYPE != "REVE_REVENUE") %>% 
  adorn_totals("row") %>% 
  mutate(TYPE = case_when(TYPE == 'Total' ~ 'REVE_REVENUE', TRUE ~ TYPE))
  
data_temp <- data_temp %>% select(-TYPE)
rownames(data_temp) <- data_raw$TYPE

new_reve_other <- t(colSums(rbind (data_temp['REVE_OTHER',], data_temp['REVE_EXCEPTIONAL',]), na.rm=TRUE))
data_temp['REVE_OTHER',] <- new_reve_other
data_temp$TYPE <- data_raw$TYPE

#totals for percentages
ert_reve_total <- data_temp[nrow(data_temp),'ERT'] %>% pull()
trm_reve_total <- data_temp[nrow(data_temp),'TRM'] %>% pull()

# prepare data for table
data_table <- data_temp %>% 
  mutate_at(vars(-TYPE), ~ as.numeric(.) /1000000) %>% 
  filter(TYPE != 'REVE_DELEGATION', TYPE != 'REVE_EXCEPTIONAL', TYPE != 'REVE_DELEGATION') %>% 
  mutate(
    ERT_F = if_else(
            TYPE == 'REVE_AIRPORT','n.a.',
             as.character(if_else(ERT<1.5,
                                        format(round(ERT,1), nsmall =1 ,big.mark= " "),
                                        format(round(ERT,0), nsmall =0 ,big.mark= " "))
    )),
    TRM_F = as.character(if_else(TRM<1.5,
                                        format(round(TRM,1), nsmall =1 ,big.mark= " "),
                                        format(round(TRM,0), nsmall =0 ,big.mark= " "))
    ),
    ERT_PERC = if_else(
            TYPE == 'REVE_AIRPORT','n.a.',
            as.character(paste0(round(ERT/ert_reve_total*100000000,
                                              if_else(ERT/ert_reve_total*100000000 <0.5,2,1)),
                                        "%"))
           ),
    TRM_PERC = as.character(paste0(round(TRM/trm_reve_total*100000000,
                                              if_else(TRM/trm_reve_total*100000000 <0.5,2,1)),
                                        "%")),
                                 ) %>% 
    mutate(LABEL = case_when(
           TYPE == 'REVE_CHARGE' ~ "Income from charges",
           TYPE == 'REVE_AIRPORT' ~ "Income from airport operators",
           TYPE == 'REVE_MILITARY' ~ "Income from the military",
           TYPE == 'REVE_EXEMPT_FLT' ~ "Income in respect of exempted flights",
           TYPE == 'REVE_DOMESTIC' ~ "Income from domestic goverment", 
           TYPE == 'REVE_FINANCIAL' ~ "Financial income",
           TYPE == 'REVE_OTHER' ~ "Other income (incl. exceptional revenue item)",
           TYPE == 'REVE_REVENUE' ~ ""
         )
         )%>% 
  select(ERT_F,ERT_PERC, LABEL, TRM_PERC, TRM_F)


##plot table
table_reve <- reactable(
  data_table,
  bordered = TRUE,
  pagination = FALSE,
  striped = FALSE,
  compact = TRUE,
  highlight = TRUE,
  defaultColDef = colDef(style=list("font-size" = "11px", "white-space"= "wrap"),
                         align = "right",
                         headerStyle = list(background = "#538DD5", color = "white", fontSize = "11px", style=list("white-space"= "wrap")),
                         footerStyle = list(fontWeight = "bold", fontSize = "11px", style=list("white-space"= "wrap"))
  ),
  columns = list(
    ERT_F = colDef(name="En-route",minWidth = 15),
    ERT_PERC = colDef(name="%",minWidth = 15),
    LABEL = colDef(name="Gate-to-gate revenues (\u20AC M)", minWidth = 40, align = "center"),
    TRM_PERC = colDef(name="%",minWidth = 15),
    TRM_F = colDef(name="Terminal", minWidth = 15)
    ),
  borderless = TRUE,
  rowStyle = JS(paste0("function(rowInfo) {
    if (rowInfo.index == ",nrow(data_table)-1,") {
      return { background: '#C0C0C0'}
    } 
  }")
  )
)

table_reve
```